### PR TITLE
Stage update

### PR DESCRIPTION
**Pull request by maciejtreder**

### CODE REVIEW

**Comment by maciejtreder** [comment]
@yamaAtsu @c-cho 
Guys let me know when you will be done with your changes, so I will review and merge them, ok?

**Comment by c-cho** [comment]
@maciejtreder Hi, it seems that we PRed by accident, but I'd like to explain why we forked your work. Actually we're using your plugin for adding binary support in API Gateway but we found a problem that since it is designed to be triggered after the whole deployment, we have to update the stage manually to enable binary support. It takes little effort but we'd like to automate this step. So we added some code for

1. deploy the api again
2. get the latest stage's name
3. get the latest deployment id of the latest stage
4. update the stage to the latest deployment

That's all about this patch. Feel free to review and merge it if it is useful for the project, and thanks a lot for your wonderful plugin.

**Comment by maciejtreder** [comment]
@c-cho Could you review your branch with the latest changes on master? I think that version 0.3.7 covers most of your changes.

**Comment by yamaAtsu** [comment]
@maciejtreder Thank you for your reply.
We think that certainly version0.3.7 covers of ours changes.
Thank you very much for your advice.

**Comment by maciejtreder** [comment]
@yamaAtsu Are you sure? As far as I can see in your code, there is some additional method which is not present in master:

```
const updateStage = ({ restApiId, deploymentId, stageName }) => {
      setTimeout(() => {
        const req = {
          restApiId: restApiId,
          stageName: stageName,
          patchOperations: [{
            op: "replace",
            path: "/deploymentId",
            value: deploymentId
          }],
        }
        console.log('request: ' + JSON.stringify(req));
        apiGWSdk.updateStage(req, (err, data) => {
          if(err) throw new Error(err, err.stack);
          else console.log(data);
        });
      }, 2000);
    };
```

What is the purpose of it? Maybe we should close this pull request and open another?

**Pull request closed without merging**
